apiVersion: apps/v1
kind: Deployment
metadata:
  name: caas-api-app
  labels:
    app: caas-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: caas-app
  template:
    metadata:
      labels:
        app: caas-api-app
        service: caas-app
    spec:
      containers:
        - name: caas-api-app-container
          image: docker.io/alimerdan/caas:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
                path: /api/v1/health
                port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
           requests:
            memory: "50Mi"
            cpu: "25m"
           limits:
            memory: "100Mi"
            cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: caas-app
  labels:
    app: caas-api-app
    service: caas-app
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: caas-app
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: caas-horizontal-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: caas-api-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 60Mi
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 10
      selectPolicy: Max
      policies:
        - type: Pods
          value: 2
          periodSeconds: 10
        - type: Percent
          value: 10
          periodSeconds: 10
    scaleDown:
      stabilizationWindowSeconds: 30
      selectPolicy: Max
      policies:
        - type: Pods
          value: 2
          periodSeconds: 30
        - type: Percent
          value: 10
          periodSeconds: 30