apiVersion: apps/v1
kind: Deployment
metadata:
  name: caas-api-app
  labels:
    app: caas-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: caas-app
  template:
    metadata:
      labels:
        app: caas-api-app
        service: caas-app
    spec:
      containers:
        - name: caas-api-app-container
          image: docker.io/alimerdan/caas:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
                path: /api/v1/health
                port: 80
            initialDelaySeconds: 0
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
           requests:
            memory: "512Mi"
            cpu: "250m"
           limits:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: caas-app
  labels:
    app: caas-api-app
    service: caas-app
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: caas-app
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: caas-horizontal-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: caas-api-app
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 300Mi    